### PR TITLE
Added goto line, fixed search scheme

### PR DESCRIPTION
**Pull request by Smankusors**
This is for issue #1,
btw I only tried this on Windows, I don't know if this will work on other systems :/

### CODE REVIEW

**Comment by stef-k** [comment]
Thanks for your time. 

I will test on Linux and proceed accordingly. Hopefully, it will be merged later tonight.

**Comment by stef-k** [comment]
@Smankusors 

I've checked the extension on Linux and I needed to do 2 changes in order to make it work.

1. add `n-readlines` as dependency in package.json
2. change `link.target = Uri.parse("file:///" + path);` to `link.target = Uri.parse("file:" + path);` from file `links.ts` line 44.

Can you make these changes, test again on Windows and submit a pull request again?

**Comment by Smankusors** [comment]
Alright done, it's working with shorter scheme 😄

**Comment by stef-k** [comment]
Tomorrow will upload the new release, thanks.

**Pull request merged**
